// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: restaurant/restaurant.proto

package restaurant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         int32                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_restaurant_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{0}
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_restaurant_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *Menu) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableNum      int32                  `protobuf:"varint,1,opt,name=tableNum,proto3" json:"tableNum,omitempty"`
	OrderItem     *MenuItem              `protobuf:"bytes,2,opt,name=orderItem,proto3" json:"orderItem,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_restaurant_restaurant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetTableNum() int32 {
	if x != nil {
		return x.TableNum
	}
	return 0
}

func (x *Order) GetOrderItem() *MenuItem {
	if x != nil {
		return x.OrderItem
	}
	return nil
}

func (x *Order) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type OrderSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableNum      int32                  `protobuf:"varint,1,opt,name=tableNum,proto3" json:"tableNum,omitempty"`
	OrderItems    []*MenuItem            `protobuf:"bytes,2,rep,name=orderItems,proto3" json:"orderItems,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSummary) Reset() {
	*x = OrderSummary{}
	mi := &file_restaurant_restaurant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSummary) ProtoMessage() {}

func (x *OrderSummary) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSummary.ProtoReflect.Descriptor instead.
func (*OrderSummary) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{3}
}

func (x *OrderSummary) GetTableNum() int32 {
	if x != nil {
		return x.TableNum
	}
	return 0
}

func (x *OrderSummary) GetOrderItems() []*MenuItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

func (x *OrderSummary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ReviewChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	TableNum      int32                  `protobuf:"varint,2,opt,name=tableNum,proto3" json:"tableNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewChat) Reset() {
	*x = ReviewChat{}
	mi := &file_restaurant_restaurant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewChat) ProtoMessage() {}

func (x *ReviewChat) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewChat.ProtoReflect.Descriptor instead.
func (*ReviewChat) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{4}
}

func (x *ReviewChat) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ReviewChat) GetTableNum() int32 {
	if x != nil {
		return x.TableNum
	}
	return 0
}

var File_restaurant_restaurant_proto protoreflect.FileDescriptor

const file_restaurant_restaurant_proto_rawDesc = "" +
	"\n" +
	"\x1brestaurant/restaurant.proto\x12\n" +
	"restaurant\x1a\x1bgoogle/protobuf/empty.proto\"4\n" +
	"\bMenuItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x05R\x05price\"2\n" +
	"\x04Menu\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.restaurant.MenuItemR\x05items\"k\n" +
	"\x05Order\x12\x1a\n" +
	"\btableNum\x18\x01 \x01(\x05R\btableNum\x122\n" +
	"\torderItem\x18\x02 \x01(\v2\x14.restaurant.MenuItemR\torderItem\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\"v\n" +
	"\fOrderSummary\x12\x1a\n" +
	"\btableNum\x18\x01 \x01(\x05R\btableNum\x124\n" +
	"\n" +
	"orderItems\x18\x02 \x03(\v2\x14.restaurant.MenuItemR\n" +
	"orderItems\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\":\n" +
	"\n" +
	"ReviewChat\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x1a\n" +
	"\btableNum\x18\x02 \x01(\x05R\btableNum2\x85\x02\n" +
	"\n" +
	"Restaurant\x125\n" +
	"\aGetMenu\x12\x16.google.protobuf.Empty\x1a\x10.restaurant.Menu\"\x00\x12=\n" +
	"\n" +
	"PlaceOrder\x12\x11.restaurant.Order\x1a\x18.restaurant.OrderSummary\"\x00(\x01\x12A\n" +
	"\x10KitchenSubscribe\x12\x16.google.protobuf.Empty\x1a\x11.restaurant.Order\"\x000\x01\x12>\n" +
	"\x06Review\x12\x16.restaurant.ReviewChat\x1a\x16.restaurant.ReviewChat\"\x00(\x010\x01BEZCgithub.com/iamads/go-workbook/restaurant_ordering_system/restaurantb\x06proto3"

var (
	file_restaurant_restaurant_proto_rawDescOnce sync.Once
	file_restaurant_restaurant_proto_rawDescData []byte
)

func file_restaurant_restaurant_proto_rawDescGZIP() []byte {
	file_restaurant_restaurant_proto_rawDescOnce.Do(func() {
		file_restaurant_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_restaurant_restaurant_proto_rawDesc), len(file_restaurant_restaurant_proto_rawDesc)))
	})
	return file_restaurant_restaurant_proto_rawDescData
}

var file_restaurant_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_restaurant_restaurant_proto_goTypes = []any{
	(*MenuItem)(nil),      // 0: restaurant.MenuItem
	(*Menu)(nil),          // 1: restaurant.Menu
	(*Order)(nil),         // 2: restaurant.Order
	(*OrderSummary)(nil),  // 3: restaurant.OrderSummary
	(*ReviewChat)(nil),    // 4: restaurant.ReviewChat
	(*emptypb.Empty)(nil), // 5: google.protobuf.Empty
}
var file_restaurant_restaurant_proto_depIdxs = []int32{
	0, // 0: restaurant.Menu.items:type_name -> restaurant.MenuItem
	0, // 1: restaurant.Order.orderItem:type_name -> restaurant.MenuItem
	0, // 2: restaurant.OrderSummary.orderItems:type_name -> restaurant.MenuItem
	5, // 3: restaurant.Restaurant.GetMenu:input_type -> google.protobuf.Empty
	2, // 4: restaurant.Restaurant.PlaceOrder:input_type -> restaurant.Order
	5, // 5: restaurant.Restaurant.KitchenSubscribe:input_type -> google.protobuf.Empty
	4, // 6: restaurant.Restaurant.Review:input_type -> restaurant.ReviewChat
	1, // 7: restaurant.Restaurant.GetMenu:output_type -> restaurant.Menu
	3, // 8: restaurant.Restaurant.PlaceOrder:output_type -> restaurant.OrderSummary
	2, // 9: restaurant.Restaurant.KitchenSubscribe:output_type -> restaurant.Order
	4, // 10: restaurant.Restaurant.Review:output_type -> restaurant.ReviewChat
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_restaurant_restaurant_proto_init() }
func file_restaurant_restaurant_proto_init() {
	if File_restaurant_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_restaurant_restaurant_proto_rawDesc), len(file_restaurant_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restaurant_restaurant_proto_goTypes,
		DependencyIndexes: file_restaurant_restaurant_proto_depIdxs,
		MessageInfos:      file_restaurant_restaurant_proto_msgTypes,
	}.Build()
	File_restaurant_restaurant_proto = out.File
	file_restaurant_restaurant_proto_goTypes = nil
	file_restaurant_restaurant_proto_depIdxs = nil
}
