// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: restaurant/restaurant.proto

package restaurant

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Restaurant_GetMenu_FullMethodName          = "/restaurant.Restaurant/GetMenu"
	Restaurant_PlaceOrder_FullMethodName       = "/restaurant.Restaurant/PlaceOrder"
	Restaurant_KitchenSubscribe_FullMethodName = "/restaurant.Restaurant/KitchenSubscribe"
	Restaurant_Review_FullMethodName           = "/restaurant.Restaurant/Review"
)

// RestaurantClient is the client API for Restaurant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestaurantClient interface {
	GetMenu(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Menu, error)
	PlaceOrder(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Order, OrderSummary], error)
	KitchenSubscribe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Order], error)
	Review(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReviewChat, ReviewChat], error)
}

type restaurantClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurantClient(cc grpc.ClientConnInterface) RestaurantClient {
	return &restaurantClient{cc}
}

func (c *restaurantClient) GetMenu(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Menu, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Menu)
	err := c.cc.Invoke(ctx, Restaurant_GetMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantClient) PlaceOrder(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Order, OrderSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Restaurant_ServiceDesc.Streams[0], Restaurant_PlaceOrder_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Order, OrderSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Restaurant_PlaceOrderClient = grpc.ClientStreamingClient[Order, OrderSummary]

func (c *restaurantClient) KitchenSubscribe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Order], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Restaurant_ServiceDesc.Streams[1], Restaurant_KitchenSubscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Order]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Restaurant_KitchenSubscribeClient = grpc.ServerStreamingClient[Order]

func (c *restaurantClient) Review(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReviewChat, ReviewChat], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Restaurant_ServiceDesc.Streams[2], Restaurant_Review_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReviewChat, ReviewChat]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Restaurant_ReviewClient = grpc.BidiStreamingClient[ReviewChat, ReviewChat]

// RestaurantServer is the server API for Restaurant service.
// All implementations must embed UnimplementedRestaurantServer
// for forward compatibility.
type RestaurantServer interface {
	GetMenu(context.Context, *emptypb.Empty) (*Menu, error)
	PlaceOrder(grpc.ClientStreamingServer[Order, OrderSummary]) error
	KitchenSubscribe(*emptypb.Empty, grpc.ServerStreamingServer[Order]) error
	Review(grpc.BidiStreamingServer[ReviewChat, ReviewChat]) error
	mustEmbedUnimplementedRestaurantServer()
}

// UnimplementedRestaurantServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRestaurantServer struct{}

func (UnimplementedRestaurantServer) GetMenu(context.Context, *emptypb.Empty) (*Menu, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenu not implemented")
}
func (UnimplementedRestaurantServer) PlaceOrder(grpc.ClientStreamingServer[Order, OrderSummary]) error {
	return status.Error(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedRestaurantServer) KitchenSubscribe(*emptypb.Empty, grpc.ServerStreamingServer[Order]) error {
	return status.Error(codes.Unimplemented, "method KitchenSubscribe not implemented")
}
func (UnimplementedRestaurantServer) Review(grpc.BidiStreamingServer[ReviewChat, ReviewChat]) error {
	return status.Error(codes.Unimplemented, "method Review not implemented")
}
func (UnimplementedRestaurantServer) mustEmbedUnimplementedRestaurantServer() {}
func (UnimplementedRestaurantServer) testEmbeddedByValue()                    {}

// UnsafeRestaurantServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestaurantServer will
// result in compilation errors.
type UnsafeRestaurantServer interface {
	mustEmbedUnimplementedRestaurantServer()
}

func RegisterRestaurantServer(s grpc.ServiceRegistrar, srv RestaurantServer) {
	// If the following call panics, it indicates UnimplementedRestaurantServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Restaurant_ServiceDesc, srv)
}

func _Restaurant_GetMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServer).GetMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Restaurant_GetMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServer).GetMenu(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Restaurant_PlaceOrder_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RestaurantServer).PlaceOrder(&grpc.GenericServerStream[Order, OrderSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Restaurant_PlaceOrderServer = grpc.ClientStreamingServer[Order, OrderSummary]

func _Restaurant_KitchenSubscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RestaurantServer).KitchenSubscribe(m, &grpc.GenericServerStream[emptypb.Empty, Order]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Restaurant_KitchenSubscribeServer = grpc.ServerStreamingServer[Order]

func _Restaurant_Review_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RestaurantServer).Review(&grpc.GenericServerStream[ReviewChat, ReviewChat]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Restaurant_ReviewServer = grpc.BidiStreamingServer[ReviewChat, ReviewChat]

// Restaurant_ServiceDesc is the grpc.ServiceDesc for Restaurant service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Restaurant_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "restaurant.Restaurant",
	HandlerType: (*RestaurantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMenu",
			Handler:    _Restaurant_GetMenu_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PlaceOrder",
			Handler:       _Restaurant_PlaceOrder_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "KitchenSubscribe",
			Handler:       _Restaurant_KitchenSubscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Review",
			Handler:       _Restaurant_Review_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "restaurant/restaurant.proto",
}
